# Site Settings

title: "Bas(e)ic R"
baseurl: /basic-R-lesson
email: cyberhelp@sesync.org
description: ""
# styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.0
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
authors:
 - Kelly Hondula
 - Ian Carroll
lesson: 2

# Slide Settings

slide_sorter:
  - title
  - intro
  - console
#  - math
  - editor
  - types
  - dataframes
#  - load
#  - plot
  - parts
  - functions
  - stats
  - flow
  - conclude
  - solutions
  
# Jekyll

markdown: kramdown
kramdown:
  toc_levels: 2..2
collections:
  - slides
exclude:
  - README.md
  - build.R
  - "*.Rproj"
  - "*.Rmd"
