# Lesson

title: Bas(e)ic R
handouts: worksheet.R
tag: v0.1
lesson: 1
instructor: Ian Carroll
authors:
 - Kelly Hondula
 - Ian Carroll

# Slides

slide_sorter:
  - intro
  - console
  - math
  - editor
  - push
  - types
  - dataframes
  - load
  - plot
  - parts
  - functions
  - stats
  - flow
  - conclude
  - push
  - solutions

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/1.1/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0

# Jekyll

markdown: kramdown
collections:
  - slides
